/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: farooq.smurf (https://sketchfab.com/farooq.smurf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-6856376b849a47d6ae30504dd7d06543
Title: Rocket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rocket(props) {
  const { nodes, materials } = useGLTF('/models/rocket.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.body_Body_material_0.geometry}
          material={materials.Body_material}
          position={[0, 124.575, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={27.404}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fire_Yellow_material_0.geometry}
          material={materials.Yellow_material}
          position={[0, 124.575, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={27.404}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.air_Red_material_0.geometry}
          material={materials.Red_material}
          position={[0, 124.575, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[27.404, 12.954, 27.404]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_background_Metal_material_0.geometry}
          material={materials.Metal_material}
          position={[0, 301.885, 26.63]}
          rotation={[-0.153, 0, 0]}
          scale={33.355}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_Glass_material_0.geometry}
          material={materials.Glass_material}
          position={[0, 301.885, 26.63]}
          rotation={[-0.153, 0, 0]}
          scale={33.355}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.red_Red_material_0.geometry}
          material={materials.Red_material}
          position={[0, 124.575, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={27.404}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.steel_Steel_material_0.geometry}
          material={materials.Steel_material}
          position={[0, 348.473, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={12.667}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/rocket.glb')
